<?php

namespace VinilShopBundle\Repository;

/**
 * advertising_sliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Advertising_sliderRepository extends \Doctrine\ORM\EntityRepository
{
}
