<?php

namespace VinilShopBundle\Repository;

/**
 * Attribute_nameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Attribute_nameRepository extends \Doctrine\ORM\EntityRepository
{
    public function attributesOfCategory($id)
    {
        return $this
            ->createQueryBuilder('attr')
            ->join('attr.categoryes', 'c')
            ->andWhere('c.id = :id')
            ->setParameter('id',$id)
            ->getQuery()
            ->getResult();
    }
    
    public function findByName($name)
    {
        return $this
            ->createQueryBuilder('attr')
            ->andWhere('attr.name =:name')
            ->setParameter('name',$name)
            ->getQuery()
            ->getResult();
    }
}