<?php

namespace VinilShopBundle\Repository;

/**
 * Attribute_nameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Attribute_nameRepository extends \Doctrine\ORM\EntityRepository
{

}
