<?php

namespace VinilShopBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function findTree()
    {

        return $this
            ->createQueryBuilder('category')
            ->leftJoin('category.children','children')
            ->addSelect('children')
            ->andWhere('category.parent is Null')
            ->getQuery()
            ->getResult();
    }

    public function parentCategories()
    {
        return $this
            ->createQueryBuilder('category')
            ->Where('category.parentCategory = false')
            ->getQuery()
            ->getResult();
    }
}
