<?php

namespace VinilShopBundle\Repository;


/**
 * ProductInOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductInOrderRepository extends \Doctrine\ORM\EntityRepository
{

}
